version: "3.8"

services:
  client:
    image: kurtyoon/dgu-portal-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    image: kurtyoon/dgu-portal-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
