version: "3.8"

services:
  nginx:
    image: kurtyoon/dgu-portal-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - client
      - server

  client:
    image: kurtyoon/dgu-portal-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    image: kurtyoon/dgu-portal-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  crawler:
    image: kurtyoon/dgu-portal-crawler:latest
    build:
      context: ./crawling
      dockerfile: Dockerfile
    depends_on:
      - database

  database:
    image: kurtyoon/dgu-portal-database:latest
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/data:/var/lib/mysql

volumes:
  mysql-data: {}
